import React, { createContext, useContext, useState } from 'react';

const vi = {
  // Sidebar
  nav_dashboard: 'Bảng điều khiển',
  nav_books: 'Quản lý sách',
  nav_borrow: 'Mượn / Trả sách',
  nav_members: 'Độc giả',
  nav_overdue: 'Quá hạn',
  nav_reports: 'Thống kê',
  nav_settings: 'Cài đặt',
  nav_overview: 'Tổng quan',
  nav_management: 'Quản lý',
  nav_system: 'Hệ thống',
  // Stats
  stat_books: 'Tổng số sách',
  stat_members: 'Độc giả',
  stat_on_loan: 'Đang mượn',
  stat_overdue: 'Quá hạn',
  // Books
  book_list: 'Danh sách sách',
  book_add: 'Thêm sách',
  book_edit: 'Chỉnh sửa sách',
  book_delete: 'Xóa sách',
  book_title: 'Tên sách',
  book_author: 'Tác giả',
  book_year: 'Năm xuất bản',
  book_genre: 'Thể loại',
  book_qty: 'Số lượng',
  book_available: 'Có sẵn',
  book_isbn: 'ISBN',
  book_publisher: 'Nhà xuất bản',
  book_status: 'Trạng thái',
  book_actions: 'Thao tác',
  status_available: 'Có sẵn',
  status_on_loan: 'Đã mượn',
  status_out_of_stock: 'Hết sách',
  // Members
  member_list: 'Danh sách độc giả',
  member_add: 'Thêm độc giả',
  member_name: 'Họ tên',
  member_card: 'Mã thẻ',
  member_email: 'Email',
  member_phone: 'Điện thoại',
  member_borrowing: 'Đang mượn',
  member_history: 'Lịch sử',
  member_since: 'Ngày đăng ký',
  member_active: 'Hoạt động',
  member_suspended: 'Tạm khóa',
  // Borrow
  borrow_issue: 'Cho mượn sách',
  borrow_return: 'Nhận trả sách',
  borrow_member_id: 'Mã thẻ độc giả',
  borrow_book_search: 'ISBN hoặc tên sách',
  borrow_period: 'Số ngày mượn',
  borrow_condition: 'Tình trạng sách',
  borrow_btn_issue: 'Cho mượn',
  borrow_btn_return: 'Nhận trả',
  borrow_date: 'Ngày mượn',
  borrow_due: 'Hạn trả',
  condition_good: 'Tốt',
  condition_fair: 'Bình thường',
  condition_damaged: 'Hư hỏng',
  // Overdue
  overdue_title: 'Danh sách quá hạn',
  overdue_days: 'Quá hạn (ngày)',
  overdue_fine: 'Tiền phạt',
  overdue_remind: 'Nhắc',
  overdue_remind_all: 'Nhắc tất cả',
  // Reports
  reports_monthly: 'Lượt mượn tháng này',
  reports_returned: 'Lượt trả tháng này',
  reports_fines: 'Phí phạt thu được',
  reports_new_members: 'Độc giả mới',
  reports_chart: 'Biểu đồ mượn sách',
  reports_export: 'Xuất Excel',
  // Common
  search_placeholder: 'Tìm kiếm...',
  btn_save: 'Lưu',
  btn_cancel: 'Hủy',
  btn_add: 'Thêm',
  btn_edit: 'Sửa',
  btn_delete: 'Xóa',
  btn_close: 'Đóng',
  btn_export: 'Xuất',
  filter_all: 'Tất cả',
  today: 'Hôm nay',
  this_week: 'Tuần này',
  this_month: 'Tháng này',
  genre_literature: 'Văn học',
  genre_science: 'Khoa học',
  genre_history: 'Lịch sử',
  genre_economics: 'Kinh tế',
  genre_children: 'Thiếu nhi',
  genre_technical: 'Kỹ thuật',
  genre_skills: 'Kỹ năng',
  overdue_warning_title: 'Cảnh báo quá hạn',
  overdue_warning_msg: 'sách đã quá hạn trả. Vui lòng liên hệ độc giả để nhắc nhở.',
  recently_borrowed: 'Sách được mượn gần đây',
  popular_genres: 'Thể loại phổ biến',
  recent_activity: 'Hoạt động gần đây',
  page_showing: 'Hiển thị',
  page_of: '/',
  loading: 'Đang tải...',
  error_required: 'Vui lòng điền đầy đủ thông tin.',
  success_add: 'Đã thêm thành công!',
  success_edit: 'Đã cập nhật thành công!',
  success_delete: 'Đã xóa thành công!',
  success_issue: 'Đã cho mượn thành công!',
  success_return: 'Đã nhận trả sách thành công!',
  success_remind: 'Đã gửi nhắc nhở!',
};

const en = {
  nav_dashboard: 'Dashboard',
  nav_books: 'Book Management',
  nav_borrow: 'Borrow / Return',
  nav_members: 'Members',
  nav_overdue: 'Overdue',
  nav_reports: 'Reports',
  nav_settings: 'Settings',
  nav_overview: 'Overview',
  nav_management: 'Management',
  nav_system: 'System',
  stat_books: 'Total Books',
  stat_members: 'Members',
  stat_on_loan: 'On Loan',
  stat_overdue: 'Overdue',
  book_list: 'Book List',
  book_add: 'Add Book',
  book_edit: 'Edit Book',
  book_delete: 'Delete Book',
  book_title: 'Book Title',
  book_author: 'Author',
  book_year: 'Year',
  book_genre: 'Genre',
  book_qty: 'Quantity',
  book_available: 'Available',
  book_isbn: 'ISBN',
  book_publisher: 'Publisher',
  book_status: 'Status',
  book_actions: 'Actions',
  status_available: 'Available',
  status_on_loan: 'On Loan',
  status_out_of_stock: 'Out of Stock',
  member_list: 'Member List',
  member_add: 'Add Member',
  member_name: 'Full Name',
  member_card: 'Card ID',
  member_email: 'Email',
  member_phone: 'Phone',
  member_borrowing: 'Borrowing',
  member_history: 'History',
  member_since: 'Member Since',
  member_active: 'Active',
  member_suspended: 'Suspended',
  borrow_issue: 'Issue Book',
  borrow_return: 'Return Book',
  borrow_member_id: 'Member ID',
  borrow_book_search: 'ISBN or Title',
  borrow_period: 'Loan Period',
  borrow_condition: 'Book Condition',
  borrow_btn_issue: 'Issue',
  borrow_btn_return: 'Return',
  borrow_date: 'Borrowed',
  borrow_due: 'Due Date',
  condition_good: 'Good',
  condition_fair: 'Fair',
  condition_damaged: 'Damaged',
  overdue_title: 'Overdue List',
  overdue_days: 'Overdue (days)',
  overdue_fine: 'Fine',
  overdue_remind: 'Remind',
  overdue_remind_all: 'Remind All',
  reports_monthly: 'Borrows This Month',
  reports_returned: 'Returns This Month',
  reports_fines: 'Fines Collected',
  reports_new_members: 'New Members',
  reports_chart: 'Borrowing Chart',
  reports_export: 'Export Excel',
  search_placeholder: 'Search...',
  btn_save: 'Save',
  btn_cancel: 'Cancel',
  btn_add: 'Add',
  btn_edit: 'Edit',
  btn_delete: 'Delete',
  btn_close: 'Close',
  btn_export: 'Export',
  filter_all: 'All',
  today: 'Today',
  this_week: 'This Week',
  this_month: 'This Month',
  genre_literature: 'Literature',
  genre_science: 'Science',
  genre_history: 'History',
  genre_economics: 'Economics',
  genre_children: "Children's",
  genre_technical: 'Technical',
  genre_skills: 'Self-Help',
  overdue_warning_title: 'Overdue Warning',
  overdue_warning_msg: 'books are overdue. Please contact readers to remind them.',
  recently_borrowed: 'Recently Borrowed',
  popular_genres: 'Popular Genres',
  recent_activity: 'Recent Activity',
  page_showing: 'Showing',
  page_of: 'of',
  loading: 'Loading...',
  error_required: 'Please fill in all required fields.',
  success_add: 'Added successfully!',
  success_edit: 'Updated successfully!',
  success_delete: 'Deleted successfully!',
  success_issue: 'Book issued successfully!',
  success_return: 'Book returned successfully!',
  success_remind: 'Reminder sent!',
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState('vi');
  const t = (key) => (lang === 'vi' ? vi[key] : en[key]) || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
export { vi, en };
